#!/usr/bin/env python3
"""Build the Olympic NOC-to-CShapes crosswalk from pinned public sources.

The existing crosswalk is never read as build input. Its published SHA-256 is
used only as a regression contract: the independently generated bytes must be
identical to the committed artifact.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable
from difflib import SequenceMatcher
import hashlib
import json
import lzma
from pathlib import Path
import re
import tarfile
import tempfile

import pandas as pd

HERE = Path(__file__).resolve().parent
MANIFEST_PATH = HERE / "source_manifest.json"
DEFAULT_OLYMPIC_SOURCE = HERE.parent / "olympics" / "120_years_olympic_history_OG.csv"
DEFAULT_EXTERNAL_DIR = HERE / "external_sources"
DEFAULT_OUTPUT = HERE / "olympic_geography_mapping.csv"

OLYMPIC_YEARS = [1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988]
SNAPSHOT_MONTH_DAY = "07-01"
OUTPUT_COLUMNS = ["NOC", "StartYear", "EndYear", "Country", "GwCodes", "Status", "Reason"]

NON_SOVEREIGN_REASON = (
    "Olympic delegation does not correspond to an independent sovereign-state "
    "geometry in the adopted CShapes choropleth."
)
NO_GEOMETRY_REASON = (
    "No corresponding geometry is available in the adopted CShapes/Gleditsch-Ward "
    "sovereign-state basemap for this Olympic scope."
)
COMPOSITE_REASON = (
    "Composite Olympic delegation is not represented as a single sovereign CShapes state."
)

# Source-backed historical exceptions that cannot be inferred from string/code
# conversion alone. See SOURCE.md for the evidence supporting each rule.
COMPOSITE_RULES = {
    ("GER", 1956, 1964): ("United Team of Germany", (260, 265)),
    ("UAR", 1960, 1960): ("United Arab Republic", (651, 652)),
}
HISTORICAL_NON_SOVEREIGN_NOCS = {"AHO", "SAA"}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def require_sha256(path: Path, expected: str, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing {label}: {path}")
    actual = sha256(path)
    if actual != expected:
        raise ValueError(f"Unexpected {label} checksum: {actual}; expected {expected}")


def load_cshapes_features(package_path: Path) -> list[dict]:
    member_name = "cshapes/inst/extdata/cshapes_2_gw.topojson.xz"
    with tarfile.open(package_path, "r:gz") as archive:
        member = archive.getmember(member_name)
        handle = archive.extractfile(member)
        if handle is None:
            raise ValueError(f"Cannot read {member_name} from {package_path}")
        topology = json.loads(lzma.decompress(handle.read()).decode("utf-8"))

    objects = topology.get("objects", {})
    if len(objects) != 1:
        raise ValueError("Expected exactly one object in the CShapes GW topology")
    return [geometry["properties"] for geometry in next(iter(objects.values()))["geometries"]]


def active_cshapes_by_year(features: Iterable[dict]) -> dict[int, dict[int, dict]]:
    by_year: dict[int, dict[int, dict]] = {}
    features = list(features)
    for year in OLYMPIC_YEARS:
        snapshot = f"{year}-{SNAPSHOT_MONTH_DAY}"
        active = {
            int(feature["gwcode"]): feature
            for feature in features
            if feature["start"] <= snapshot <= feature["end"]
        }
        if not active:
            raise ValueError(f"No active CShapes entities for {snapshot}")
        by_year[year] = active
    return by_year


def compile_countrycode_patterns(path: Path) -> list[tuple[re.Pattern[str], int | None]]:
    codelist = pd.read_csv(path)
    patterns: list[tuple[re.Pattern[str], int | None]] = []
    for pattern_text, gw_code in codelist[
        ["country.name.en.regex", "gwn"]
    ].itertuples(index=False, name=None):
        if pd.isna(pattern_text):
            continue
        patterns.append(
            (
                re.compile(str(pattern_text), flags=re.IGNORECASE),
                None if pd.isna(gw_code) else int(gw_code),
            )
        )
    return patterns


def gleditsch_ward_code(
    name: str, patterns: Iterable[tuple[re.Pattern[str], int | None]]
) -> int | None:
    matches = [code for pattern, code in patterns if pattern.search(name) and code is not None]
    return matches[0] if matches else None


def load_country_profiles(path: Path) -> dict[str, dict]:
    countries = json.loads(path.read_text(encoding="utf-8"))
    return {country["cioc"]: country for country in countries if country.get("cioc")}


def olympic_participants(path: Path) -> tuple[pd.DataFrame, dict[str, str]]:
    raw = pd.read_csv(path, delimiter=";", low_memory=False)
    required = {"NOC", "Year", "Season", "Team"}
    missing = required - set(raw.columns)
    if missing:
        raise ValueError(f"Olympic source is missing columns: {sorted(missing)}")

    scope = raw[(raw["Season"] == "Summer") & raw["Year"].isin(OLYMPIC_YEARS)].copy()
    scope["TeamClean"] = (
        scope["Team"].astype(str).str.replace(r"-\d+$", "", regex=True).str.strip()
    )
    labels = (
        scope.groupby("NOC")["TeamClean"]
        .agg(lambda values: values.value_counts().index[0])
        .to_dict()
    )
    participants = (
        scope[["Year", "NOC"]]
        .drop_duplicates()
        .sort_values(["NOC", "Year"])
        .reset_index(drop=True)
    )
    return participants, labels


def display_name(noc: str, year: int, modal_label: str) -> str:
    for (rule_noc, start, end), (name, _) in COMPOSITE_RULES.items():
        if noc == rule_noc and start <= year <= end:
            return name
    # The athlete file retrospectively labels the 1960/1964 ZIM records as
    # Zimbabwe. Olympedia records 1964 as Rhodesia and the 1980 return as Zimbabwe.
    if noc == "ZIM" and year < 1980:
        return "Rhodesia"
    return modal_label


def composite_codes(noc: str, year: int) -> tuple[int, ...] | None:
    for (rule_noc, start, end), (_, codes) in COMPOSITE_RULES.items():
        if noc == rule_noc and start <= year <= end:
            return codes
    return None


def best_cshapes_similarity(
    name: str,
    active: dict[int, dict],
    statuses: set[str] | None = None,
) -> tuple[float, int | None, dict | None]:
    candidates = []
    for code, feature in active.items():
        if statuses is not None and feature["status"] not in statuses:
            continue
        score = SequenceMatcher(
            None, name.casefold(), feature["country_name"].casefold()
        ).ratio()
        candidates.append((score, code, feature))
    return max(candidates, default=(0.0, None, None), key=lambda item: item[0])


def resolve_codes(
    noc: str,
    year: int,
    name: str,
    active: dict[int, dict],
    patterns: list[tuple[re.Pattern[str], int | None]],
    profiles: dict[str, dict],
) -> tuple[int, ...]:
    explicit = composite_codes(noc, year)
    if explicit is not None:
        if not set(explicit) <= set(active):
            raise ValueError(f"Composite codes are not active for {noc} {year}: {explicit}")
        return explicit

    gw_code = gleditsch_ward_code(name, patterns)
    if gw_code in active:
        return (gw_code,)

    # A historical name may resolve to an earlier GW entity. If one currently
    # active CShapes name starts with the same label, use that unique successor.
    if gw_code is not None:
        starts_with = [
            code
            for code, feature in active.items()
            if feature["country_name"].casefold().startswith(name.casefold())
        ]
        if len(starts_with) == 1:
            return (starts_with[0],)

    profile = profiles.get(noc)
    if profile is not None:
        return ()

    # Historical labels absent from the modern IOC dictionary receive one
    # conservative fuzzy attempt. This resolves Malaya -> Malaysia; the high
    # threshold and uniqueness margin prevent dependency names from leaking in.
    score, code, _ = best_cshapes_similarity(name, active)
    ranked = sorted(
        SequenceMatcher(None, name.casefold(), feature["country_name"].casefold()).ratio()
        for feature in active.values()
    )
    second = ranked[-2] if len(ranked) > 1 else 0.0
    if score >= 0.84 and score - second >= 0.05:
        return (int(code),)
    return ()


def exclusion(
    noc: str,
    year: int,
    name: str,
    active: dict[int, dict],
    profiles: dict[str, dict],
) -> tuple[str, str]:
    if "Federation" in name:
        return "excluded_composite_delegation", COMPOSITE_REASON

    profile = profiles.get(noc)
    if (
        profile is not None and profile.get("independent") is False
    ) or noc in HISTORICAL_NON_SOVEREIGN_NOCS:
        return "excluded_non_sovereign", NON_SOVEREIGN_REASON

    score, _, _ = best_cshapes_similarity(
        name, active, {"colony", "protectorate", "mandate", "occupied"}
    )
    if score >= 0.70:
        return "excluded_non_sovereign", NON_SOVEREIGN_REASON

    if noc == "VNM" and year == 1952:
        reason = "South Vietnam has no corresponding sovereign CShapes/Gleditsch-Ward geometry in the 1952 snapshot."
    elif noc == "RHO" and year == 1960:
        reason = "The 1960 Rhodesian Olympic delegation has no corresponding sovereign geometry in the adopted CShapes snapshot."
    elif noc == "ZIM" and year == 1960:
        reason = "The 1960 Rhodesian/Zimbabwe entry has no corresponding sovereign geometry in the adopted CShapes snapshot."
    else:
        reason = NO_GEOMETRY_REASON
    return "excluded_no_cshapes_geometry", reason


def compress_year_rows(rows: pd.DataFrame) -> pd.DataFrame:
    output: list[dict] = []
    comparison_fields = ["Country", "GwCodes", "Status", "Reason"]
    for noc, group in rows.groupby("NOC", sort=True):
        current: dict | None = None
        current_key: tuple | None = None
        for row in group.sort_values("Year").to_dict("records"):
            key = tuple(row[field] for field in comparison_fields)
            if current is not None and key == current_key:
                current["EndYear"] = int(row["Year"])
                continue
            if current is not None:
                output.append(current)
            current = {
                "NOC": noc,
                "StartYear": int(row["Year"]),
                "EndYear": int(row["Year"]),
                **{field: row[field] for field in comparison_fields},
            }
            current_key = key
        if current is not None:
            output.append(current)
    return pd.DataFrame(output, columns=OUTPUT_COLUMNS)


def validate(
    rows: pd.DataFrame,
    mapping: pd.DataFrame,
    active_by_year: dict[int, dict],
) -> None:
    errors: list[str] = []
    owners: dict[tuple[int, int], str] = {}

    for participant in rows.itertuples(index=False):
        matches = mapping[
            mapping["NOC"].eq(participant.NOC)
            & mapping["StartYear"].le(int(participant.Year))
            & mapping["EndYear"].ge(int(participant.Year))
        ]
        if len(matches) != 1:
            errors.append(f"{participant.NOC} {participant.Year} resolves to {len(matches)} rules")
            continue
        rule = matches.iloc[0]
        codes = [int(code) for code in str(rule.GwCodes).split(";") if code]
        if rule.Status == "mapped" and not codes:
            errors.append(f"Mapped row has no code: {participant.NOC} {participant.Year}")
        if rule.Status != "mapped" and not str(rule.Reason).strip():
            errors.append(f"Excluded row has no reason: {participant.NOC} {participant.Year}")
        for code in codes:
            if code not in active_by_year[int(participant.Year)]:
                errors.append(f"GW {code} is inactive for {participant.NOC} {participant.Year}")
            key = (int(participant.Year), code)
            previous = owners.get(key)
            if previous is not None and previous != participant.NOC:
                errors.append(f"GW collision {key}: {previous} and {participant.NOC}")
            owners[key] = participant.NOC

    if errors:
        raise ValueError("Crosswalk validation failed:\n  - " + "\n  - ".join(errors))


def build(
    olympic_source: Path,
    external_dir: Path,
    output: Path,
    manifest: dict,
) -> None:
    sources = manifest["sources"]
    cshapes_path = external_dir / sources["cshapes"]["filename"]
    countrycode_path = external_dir / sources["countrycode"]["filename"]
    countries_path = external_dir / sources["countries"]["filename"]

    require_sha256(olympic_source, sources["olympic_history"]["sha256"], "Olympic source")
    require_sha256(cshapes_path, sources["cshapes"]["sha256"], "CShapes source")
    require_sha256(countrycode_path, sources["countrycode"]["sha256"], "countrycode source")
    require_sha256(countries_path, sources["countries"]["sha256"], "country-status source")

    participants, labels = olympic_participants(olympic_source)
    features = load_cshapes_features(cshapes_path)
    active_by_year = active_cshapes_by_year(features)
    patterns = compile_countrycode_patterns(countrycode_path)
    profiles = load_country_profiles(countries_path)

    year_rows: list[dict] = []
    for participant in participants.itertuples(index=False):
        year = int(participant.Year)
        noc = str(participant.NOC)
        name = display_name(noc, year, labels[noc])
        codes = resolve_codes(noc, year, name, active_by_year[year], patterns, profiles)
        if codes:
            status, reason = "mapped", ""
        else:
            status, reason = exclusion(noc, year, name, active_by_year[year], profiles)
        year_rows.append(
            {
                "Year": year,
                "NOC": noc,
                "Country": name,
                "GwCodes": ";".join(str(code) for code in codes),
                "Status": status,
                "Reason": reason,
            }
        )

    mapping = compress_year_rows(pd.DataFrame(year_rows))
    validate(participants, mapping, active_by_year)

    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="",
        prefix=f".{output.name}.",
        dir=output.parent,
        delete=False,
    ) as temporary:
        temporary_path = Path(temporary.name)
        mapping.to_csv(temporary, index=False, lineterminator="\n")

    try:
        actual = sha256(temporary_path)
        expected = manifest["expected_output"]["sha256"]
        if actual != expected:
            raise ValueError(f"Generated output checksum is {actual}; expected {expected}")
        temporary_path.replace(output)
    finally:
        temporary_path.unlink(missing_ok=True)

    print(
        f"Wrote {output}: {len(mapping)} rules from {participants.NOC.nunique()} NOCs; "
        f"SHA-256 {actual}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--olympic-source", type=Path, default=DEFAULT_OLYMPIC_SOURCE)
    parser.add_argument("--external-dir", type=Path, default=DEFAULT_EXTERNAL_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate to a temporary file and compare it byte-for-byte with --output.",
    )
    args = parser.parse_args()
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

    if not args.check:
        build(args.olympic_source, args.external_dir, args.output, manifest)
        return

    if not args.output.exists():
        raise FileNotFoundError(f"Cannot check missing committed output: {args.output}")
    with tempfile.TemporaryDirectory(prefix="olympic-geography-check-") as temporary_dir:
        generated = Path(temporary_dir) / args.output.name
        build(args.olympic_source, args.external_dir, generated, manifest)
        if generated.read_bytes() != args.output.read_bytes():
            raise ValueError(f"Generated file differs byte-for-byte from {args.output}")
    print(f"CHECK SUCCESSFUL: generated bytes equal {args.output}")


if __name__ == "__main__":
    main()
